import './catalogo-serch';
import './banner-main';
import './header-main';
import './common-component/formulario-generico';
import './dm/banner-dm';
import './form-banner'
import './pruebas/visual-test'
import './pruebas/controlador-test'
import './dm/catalogo-dm'